FROM ubuntu:20.04

RUN apt-get update && \
    apt-get install -y \
    python3 python3-pip build-essential libssl-dev libffi-dev python3-dev python3-testresources && \
    python3 --version && \
    pip3 install numpy && \
    pip3 install tensorflow